apiVersion: v1
kind: Service
metadata:
  name: ceph-exporter
  labels:
    k8s-app: ceph-exporter
    app: ceph-exporter
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CephExporter"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9128"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9128
    protocol: TCP
  selector:
    app: ceph-exporter
