global:
  resolve_timeout: 1m
  smtp_hello: 'your_smtp_smarthost'
  smtp_smarthost: 'your_smtp_smarthost'
  smtp_from: 'your_smtp_from'
  smtp_auth_username: 'your_smtp_user'
  smtp_auth_password: 'your_smtp_pass'
  smtp_require_tls: false
templates:
- '/etc/alertmanager/config/*.tmpl'
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 60s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
  - receiver: 'webhook'
    group_wait: 30s
    group_interval: 1m
    repeat_interval: 1h
    match_re:
      resource_type: node
    continue: true
  - receiver: 'default-receiver'
    match_re:
      resource_type: node|service
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  # Apply inhibition if the alertname is the same.
  equal: ['alertname', 'cluster', 'service']
receivers:
- name: 'default-receiver'
  email_configs:
  - to: 'your_alert_email_address'
    send_resolved: false
    headers: { Subject: "[WARN] Alerts Email" }
    html: '{{ template "email.default.html" . }}'
- name: 'webhook'
  webhook_configs:
  - url: 'http://alert-queen:5000/alerts'  #Look at https://github.com/aixeshunter/alertmanager-webhook
    send_resolved: true