apiVersion: v1
kind: Service
metadata:
  name: glusterfs-exporter
  labels:
    k8s-app: glusterfs-exporter
    app: glusterfs-exporter
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "GlusterfsExporter"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9189"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9189
    protocol: TCP
  selector:
    app: glusterfs-exporter