apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 31503
    targetPort: http
  selector:
    app: grafana
  type: NodePort