apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: main
  name: alertmanager-main
spec:
  ports:
  - name: web
    port: 9093
    protocol: TCP
    nodePort: 31501
    targetPort: web
  selector:
    alertmanager: main
  type: NodePort