apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: main
  labels:
    alertmanager: main
spec:
  replicas: 3
  baseImage: quay.io/prometheus/alertmanager
  version: ALERTMANAGER_VERSION
  externalUrl: ALERTMANAGER_EXTERNAL_URL
  nodeSelector:
    node_label_key: node_label_value
